name = "omniscore"
compatibility_date = "2024-04-01"
main = "worker.ts"

[assets]
directory = "dist"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "omniscore"
database_id = "049e36c3-fae7-442b-ac1c-6cd0c34a09f4" # Replace with your actual D1 database ID

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "omniscore-bucket"

[vars]
# You need to set these in Cloudflare Pages settings or .dev.vars for local dev
# JWT_SECRET = "..."
# APP_URL = "http://localhost:3000"
# AI_API_KEY = "..."
# AI_API_URL = "..."
